# -*- encoding: utf-8 -*-

=begin
#Docker HUB API

#Docker Hub is a service provided by Docker for finding and sharing container images with your team.  It is the world's largest library and community for container images.  In addition to the [Docker Hub UI](https://docs.docker.com/docker-hub/) and [Docker Hub CLI tool](https://github.com/docker/hub-tool#readme) (currently experimental), Docker provides an API that allows you to interact with Docker Hub.  Browse through the Docker Hub API documentation to explore the supported endpoints. 

The version of the OpenAPI document: 2-beta

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.2.0

=end

$:.push File.expand_path("../lib", __FILE__)
require "docker-hub/version"

Gem::Specification.new do |s|
  s.name        = "docker-hub"
  s.version     = DockerHub::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["saiden-dev"]
  s.email       = ["dev@saiden.pl"]
  s.homepage    = "https://github.com/saiden-dev/docker-hub"
  s.summary     = "Ruby client for Docker Hub API"
  s.description = "Auto-generated Ruby client for Docker Hub API"
  s.license     = "MIT"
  s.required_ruby_version = ">= 3.0"
  s.metadata    = {}

  s.add_runtime_dependency 'typhoeus', '~> 1.0', '>= 1.0.1'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = `find *`.split("\n").uniq.sort.select { |f| !f.empty? }
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
