=begin
#Docker HUB API

#Docker Hub is a service provided by Docker for finding and sharing container images with your team.  It is the world's largest library and community for container images.  In addition to the [Docker Hub UI](https://docs.docker.com/docker-hub/) and [Docker Hub CLI tool](https://github.com/docker/hub-tool#readme) (currently experimental), Docker provides an API that allows you to interact with Docker Hub.  Browse through the Docker Hub API documentation to explore the supported endpoints. 

The version of the OpenAPI document: 2-beta

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

# Common files
require 'docker-hub/api_client'
require 'docker-hub/api_error'
require 'docker-hub/api_model_base'
require 'docker-hub/version'
require 'docker-hub/configuration'

# Models
require 'docker-hub/models/access_token'
require 'docker-hub/models/audit_log'
require 'docker-hub/models/audit_log_action'
require 'docker-hub/models/audit_log_actions'
require 'docker-hub/models/auth_create_access_token_request'
require 'docker-hub/models/auth_create_token_response'
require 'docker-hub/models/bulk_invite'
require 'docker-hub/models/bulk_invite_invitees_inner'
require 'docker-hub/models/category'
require 'docker-hub/models/create_access_token_request'
require 'docker-hub/models/create_org_access_token_request'
require 'docker-hub/models/create_org_access_token_response'
require 'docker-hub/models/email_address'
require 'docker-hub/models/email_with_username'
require 'docker-hub/models/error'
require 'docker-hub/models/get_access_tokens_response'
require 'docker-hub/models/get_audit_actions_response'
require 'docker-hub/models/get_audit_logs_response'
require 'docker-hub/models/get_org_access_token_response'
require 'docker-hub/models/get_org_access_tokens_response'
require 'docker-hub/models/group_member'
require 'docker-hub/models/image'
require 'docker-hub/models/immutable_tags_settings'
require 'docker-hub/models/immutable_tags_verify_request'
require 'docker-hub/models/immutable_tags_verify_response'
require 'docker-hub/models/invite'
require 'docker-hub/models/layer'
require 'docker-hub/models/legacy_email_address'
require 'docker-hub/models/list_repositories_response'
require 'docker-hub/models/org_access_token'
require 'docker-hub/models/org_access_token_resource'
require 'docker-hub/models/org_group'
require 'docker-hub/models/org_member'
require 'docker-hub/models/org_member_paginated'
require 'docker-hub/models/org_settings'
require 'docker-hub/models/page'
require 'docker-hub/models/paginated_tags'
require 'docker-hub/models/patch_access_token_request'
require 'docker-hub/models/post_users2_fa_login_error_response'
require 'docker-hub/models/post_users_login_error_response'
require 'docker-hub/models/post_users_login_success_response'
require 'docker-hub/models/protobuf_any'
require 'docker-hub/models/repo_creation_request'
require 'docker-hub/models/repo_permissions'
require 'docker-hub/models/repository_group'
require 'docker-hub/models/repository_group_creation_request'
require 'docker-hub/models/repository_info'
require 'docker-hub/models/repository_list_entry'
require 'docker-hub/models/restricted_images'
require 'docker-hub/models/rpc_status'
require 'docker-hub/models/scim_email'
require 'docker-hub/models/scim_error'
require 'docker-hub/models/scim_group'
require 'docker-hub/models/scim_resource_type'
require 'docker-hub/models/scim_schema'
require 'docker-hub/models/scim_schema_attribute'
require 'docker-hub/models/scim_schema_parent_attribute'
require 'docker-hub/models/scim_service_provider_config'
require 'docker-hub/models/scim_service_provider_config_authentication_schemes'
require 'docker-hub/models/scim_service_provider_config_bulk'
require 'docker-hub/models/scim_service_provider_config_change_password'
require 'docker-hub/models/scim_service_provider_config_filter'
require 'docker-hub/models/scim_service_provider_config_patch'
require 'docker-hub/models/scim_service_provider_config_sort'
require 'docker-hub/models/scim_user'
require 'docker-hub/models/scim_user_meta'
require 'docker-hub/models/scim_user_name'
require 'docker-hub/models/tag'
require 'docker-hub/models/team_repo'
require 'docker-hub/models/update_org_access_token_request'
require 'docker-hub/models/update_org_access_token_response'
require 'docker-hub/models/update_repository_immutable_tags_request'
require 'docker-hub/models/user'
require 'docker-hub/models/users2_fa_login_request'
require 'docker-hub/models/users_login_request'
require 'docker-hub/models/v2_access_tokens_uuid_get200_response'
require 'docker-hub/models/v2_invites_bulk_post202_response'
require 'docker-hub/models/v2_invites_bulk_post_request'
require 'docker-hub/models/v2_orgs_name_settings_put_request'
require 'docker-hub/models/v2_orgs_name_settings_put_request_restricted_images'
require 'docker-hub/models/v2_orgs_org_name_groups_get200_response'
require 'docker-hub/models/v2_orgs_org_name_groups_group_name_members_get200_response'
require 'docker-hub/models/v2_orgs_org_name_groups_group_name_members_post_request'
require 'docker-hub/models/v2_orgs_org_name_groups_group_name_patch_request'
require 'docker-hub/models/v2_orgs_org_name_groups_post_request'
require 'docker-hub/models/v2_orgs_org_name_invites_get200_response'
require 'docker-hub/models/v2_orgs_org_name_members_export_get200_response_inner'
require 'docker-hub/models/v2_orgs_org_name_members_username_put_request'
require 'docker-hub/models/v2_scim20_resource_types_get200_response'
require 'docker-hub/models/v2_scim20_resource_types_name_get404_response'
require 'docker-hub/models/v2_scim20_schemas_get200_response'
require 'docker-hub/models/v2_scim20_service_provider_config_get401_response'
require 'docker-hub/models/v2_scim20_service_provider_config_get500_response'
require 'docker-hub/models/v2_scim20_users_get200_response'
require 'docker-hub/models/v2_scim20_users_get400_response'
require 'docker-hub/models/v2_scim20_users_get403_response'
require 'docker-hub/models/v2_scim20_users_id_put_request'
require 'docker-hub/models/v2_scim20_users_post409_response'
require 'docker-hub/models/v2_scim20_users_post_request'
require 'docker-hub/models/value_error'

# APIs
require 'docker-hub/api/access_tokens_api'
require 'docker-hub/api/audit_logs_api'
require 'docker-hub/api/authentication_api_api'
require 'docker-hub/api/groups_api'
require 'docker-hub/api/invites_api'
require 'docker-hub/api/org_access_tokens_api'
require 'docker-hub/api/org_settings_api'
require 'docker-hub/api/orgs_api'
require 'docker-hub/api/repositories_api'
require 'docker-hub/api/scim_api'

module DockerHub
  class << self
    # Customize default settings for the SDK using block.
    #   DockerHub.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
