=begin
#Docker HUB API

#Docker Hub is a service provided by Docker for finding and sharing container images with your team.  It is the world's largest library and community for container images.  In addition to the [Docker Hub UI](https://docs.docker.com/docker-hub/) and [Docker Hub CLI tool](https://github.com/docker/hub-tool#readme) (currently experimental), Docker provides an API that allows you to interact with Docker Hub.  Browse through the Docker Hub API documentation to explore the supported endpoints. 

The version of the OpenAPI document: 2-beta

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'spec_helper'
require 'json'

# Unit tests for DockerHub::AccessTokensApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AccessTokensApi' do
  before do
    # run before each test
    @api_instance = DockerHub::AccessTokensApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AccessTokensApi' do
    it 'should create an instance of AccessTokensApi' do
      expect(@api_instance).to be_instance_of(DockerHub::AccessTokensApi)
    end
  end

  # unit tests for v2_access_tokens_get
  # List personal access tokens
  # Returns a paginated list of personal access tokens.
  # @param [Hash] opts the optional parameters
  # @option opts [Float] :page 
  # @option opts [Float] :page_size 
  # @return [GetAccessTokensResponse]
  describe 'v2_access_tokens_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v2_access_tokens_post
  # Create personal access token
  # Creates and returns a personal access token.
  # @param create_access_token_request 
  # @param [Hash] opts the optional parameters
  # @return [AccessToken]
  describe 'v2_access_tokens_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v2_access_tokens_uuid_delete
  # Delete personal access token
  # Deletes a personal access token permanently. This cannot be undone. 
  # @param uuid 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'v2_access_tokens_uuid_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v2_access_tokens_uuid_get
  # Get personal access token
  # Returns a personal access token by UUID.
  # @param uuid 
  # @param [Hash] opts the optional parameters
  # @return [V2AccessTokensUuidGet200Response]
  describe 'v2_access_tokens_uuid_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v2_access_tokens_uuid_patch
  # Update personal access token
  # Updates a personal access token partially. You can either update the token&#39;s label or enable/disable it. 
  # @param uuid 
  # @param patch_access_token_request 
  # @param [Hash] opts the optional parameters
  # @return [AccessToken]
  describe 'v2_access_tokens_uuid_patch test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
