=begin
#Docker HUB API

#Docker Hub is a service provided by Docker for finding and sharing container images with your team.  It is the world's largest library and community for container images.  In addition to the [Docker Hub UI](https://docs.docker.com/docker-hub/) and [Docker Hub CLI tool](https://github.com/docker/hub-tool#readme) (currently experimental), Docker provides an API that allows you to interact with Docker Hub.  Browse through the Docker Hub API documentation to explore the supported endpoints. 

The version of the OpenAPI document: 2-beta

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'spec_helper'
require 'json'

# Unit tests for DockerHub::AuditLogsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AuditLogsApi' do
  before do
    # run before each test
    @api_instance = DockerHub::AuditLogsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AuditLogsApi' do
    it 'should create an instance of AuditLogsApi' do
      expect(@api_instance).to be_instance_of(DockerHub::AuditLogsApi)
    end
  end

  # unit tests for audit_logs_list_audit_actions
  # List audit log actions
  # List audit log actions for a namespace to be used as a filter for querying audit log events.  &lt;span class&#x3D;\&quot;oat\&quot;&gt;&lt;/span&gt; 
  # @param account Namespace to query audit log actions for.
  # @param [Hash] opts the optional parameters
  # @return [GetAuditActionsResponse]
  describe 'audit_logs_list_audit_actions test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for audit_logs_list_audit_logs
  # List audit log events
  # List audit log events for a given namespace.  &lt;span class&#x3D;\&quot;oat\&quot;&gt;&lt;/span&gt; 
  # @param account Namespace to query audit logs for.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :action action name one of [\&quot;repo.tag.push\&quot;, ...]. Optional parameter to filter specific audit log actions. 
  # @option opts [String] :name name. Optional parameter to filter audit log events to a specific name. For repository events, this is the name of the repository. For organization events, this is the name of the organization. For team member events, this is the username of the team member. 
  # @option opts [String] :actor actor name. Optional parameter to filter audit log events to the specific user who triggered the event. 
  # @option opts [Time] :from Start of the time window you wish to query audit events for.
  # @option opts [Time] :to End of the time window you wish to query audit events for.
  # @option opts [Integer] :page page - specify page number. Page number to get.
  # @option opts [Integer] :page_size page_size - specify page size. Number of events to return per page.
  # @return [GetAuditLogsResponse]
  describe 'audit_logs_list_audit_logs test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
