=begin
#Docker HUB API

#Docker Hub is a service provided by Docker for finding and sharing container images with your team.  It is the world's largest library and community for container images.  In addition to the [Docker Hub UI](https://docs.docker.com/docker-hub/) and [Docker Hub CLI tool](https://github.com/docker/hub-tool#readme) (currently experimental), Docker provides an API that allows you to interact with Docker Hub.  Browse through the Docker Hub API documentation to explore the supported endpoints. 

The version of the OpenAPI document: 2-beta

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'spec_helper'
require 'json'

# Unit tests for DockerHub::AuthenticationApiApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AuthenticationApiApi' do
  before do
    # run before each test
    @api_instance = DockerHub::AuthenticationApiApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AuthenticationApiApi' do
    it 'should create an instance of AuthenticationApiApi' do
      expect(@api_instance).to be_instance_of(DockerHub::AuthenticationApiApi)
    end
  end

  # unit tests for auth_create_access_token
  # Create access token
  # Creates and returns a short-lived access token in JWT format for use as a bearer when calling Docker APIs.  If successful, the access token returned should be used in the HTTP Authorization header like  &#x60;Authorization: Bearer {access_token}&#x60;.  _**If your organization has SSO enforced, you must use a personal access token (PAT) instead of a password.**_ 
  # @param [Hash] opts the optional parameters
  # @option opts [AuthCreateAccessTokenRequest] :auth_create_access_token_request 
  # @return [AuthCreateTokenResponse]
  describe 'auth_create_access_token test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for post_users2_fa_login
  # Second factor authentication
  # When a user has two-factor authentication (2FA) enabled, this is the second call to perform after &#x60;/v2/users/login&#x60; call.  Creates and returns a bearer token in JWT format that you can use to authenticate with Docker Hub APIs.  The returned token is used in the HTTP Authorization header like &#x60;Authorization: Bearer {TOKEN}&#x60;.  Most Docker Hub APIs require this token either to consume or to get detailed information. For example, to list images in a private repository. 
  # @param users2_fa_login_request Login details.
  # @param [Hash] opts the optional parameters
  # @return [PostUsersLoginSuccessResponse]
  describe 'post_users2_fa_login test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for post_users_login
  # Create an authentication token
  # Creates and returns a bearer token in JWT format that you can use to authenticate with Docker Hub APIs.  The returned token is used in the HTTP Authorization header like &#x60;Authorization: Bearer {TOKEN}&#x60;.  _**As of September 16, 2024, this route requires a personal access token (PAT) instead of a password if your organization has SSO enforced.**_  &lt;div style&#x3D;\&quot;background-color:rgb(255, 165, 0, .25); padding:5px; border-radius:4px\&quot;&gt;   &lt;strong&gt;Deprecated&lt;/strong&gt;: Use [&lt;a href&#x3D;\&quot;#tag/authentication-api/operation/AuthCreateAccessToken\&quot;&gt;Create access token&lt;/a&gt;] instead. &lt;/div&gt; 
  # @param users_login_request Login details.
  # @param [Hash] opts the optional parameters
  # @return [PostUsersLoginSuccessResponse]
  describe 'post_users_login test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
