=begin
#Docker HUB API

#Docker Hub is a service provided by Docker for finding and sharing container images with your team.  It is the world's largest library and community for container images.  In addition to the [Docker Hub UI](https://docs.docker.com/docker-hub/) and [Docker Hub CLI tool](https://github.com/docker/hub-tool#readme) (currently experimental), Docker provides an API that allows you to interact with Docker Hub.  Browse through the Docker Hub API documentation to explore the supported endpoints. 

The version of the OpenAPI document: 2-beta

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'spec_helper'
require 'json'

# Unit tests for DockerHub::GroupsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'GroupsApi' do
  before do
    # run before each test
    @api_instance = DockerHub::GroupsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of GroupsApi' do
    it 'should create an instance of GroupsApi' do
      expect(@api_instance).to be_instance_of(DockerHub::GroupsApi)
    end
  end

  # unit tests for v2_orgs_org_name_groups_get
  # Get groups of an organization
  # &lt;span class&#x3D;\&quot;oat\&quot;&gt;&lt;/span&gt; 
  # @param org_name Name of the organization (namespace).
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page Page number (starts on 1).
  # @option opts [Integer] :page_size Number of items (rows) per page.
  # @option opts [String] :username Get groups for the specified username in the organization.
  # @option opts [String] :search Get groups for the specified group in the organization.
  # @return [V2OrgsOrgNameGroupsGet200Response]
  describe 'v2_orgs_org_name_groups_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v2_orgs_org_name_groups_group_name_delete
  # Delete an organization group
  # &lt;span class&#x3D;\&quot;oat\&quot;&gt;&lt;/span&gt; 
  # @param org_name Name of the organization (namespace).
  # @param group_name Name of the group (team) in the organization.
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'v2_orgs_org_name_groups_group_name_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v2_orgs_org_name_groups_group_name_get
  # Get a group of an organization
  # &lt;span class&#x3D;\&quot;oat\&quot;&gt;&lt;/span&gt; 
  # @param org_name Name of the organization (namespace).
  # @param group_name Name of the group (team) in the organization.
  # @param [Hash] opts the optional parameters
  # @return [OrgGroup]
  describe 'v2_orgs_org_name_groups_group_name_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v2_orgs_org_name_groups_group_name_members_get
  # List members of a group
  # List the members (users) that are in a group. If user is owner of the org or has otherwise elevated permissions, they can search by email and the result will also contain emails.  &lt;span class&#x3D;\&quot;oat\&quot;&gt;&lt;/span&gt; 
  # @param org_name Name of the organization (namespace).
  # @param group_name Name of the group (team) in the organization.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page Page number (starts on 1).
  # @option opts [Integer] :page_size Number of items (rows) per page.
  # @option opts [String] :search Search members by username, full_name or email.
  # @return [V2OrgsOrgNameGroupsGroupNameMembersGet200Response]
  describe 'v2_orgs_org_name_groups_group_name_members_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v2_orgs_org_name_groups_group_name_members_post
  # Add a member to a group
  # &lt;span class&#x3D;\&quot;oat\&quot;&gt;&lt;/span&gt; 
  # @param org_name Name of the organization (namespace).
  # @param group_name Name of the group (team) in the organization.
  # @param v2_orgs_org_name_groups_group_name_members_post_request 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'v2_orgs_org_name_groups_group_name_members_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v2_orgs_org_name_groups_group_name_members_username_delete
  # Remove a user from a group
  # &lt;span class&#x3D;\&quot;oat\&quot;&gt;&lt;/span&gt; 
  # @param org_name Name of the organization (namespace).
  # @param group_name Name of the group (team) in the organization.
  # @param username Username, identifier for the user (namespace, DockerID).
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'v2_orgs_org_name_groups_group_name_members_username_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v2_orgs_org_name_groups_group_name_patch
  # Update some details for an organization group
  # &lt;span class&#x3D;\&quot;oat\&quot;&gt;&lt;/span&gt; 
  # @param org_name Name of the organization (namespace).
  # @param group_name Name of the group (team) in the organization.
  # @param [Hash] opts the optional parameters
  # @option opts [V2OrgsOrgNameGroupsGroupNamePatchRequest] :v2_orgs_org_name_groups_group_name_patch_request 
  # @return [OrgGroup]
  describe 'v2_orgs_org_name_groups_group_name_patch test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v2_orgs_org_name_groups_group_name_put
  # Update the details for an organization group
  # &lt;span class&#x3D;\&quot;oat\&quot;&gt;&lt;/span&gt; 
  # @param org_name Name of the organization (namespace).
  # @param group_name Name of the group (team) in the organization.
  # @param [Hash] opts the optional parameters
  # @option opts [V2OrgsOrgNameGroupsPostRequest] :v2_orgs_org_name_groups_post_request 
  # @return [OrgGroup]
  describe 'v2_orgs_org_name_groups_group_name_put test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v2_orgs_org_name_groups_post
  # Create a new group
  # Create a new group within an organization.  &lt;span class&#x3D;\&quot;oat\&quot;&gt;&lt;/span&gt; 
  # @param org_name Name of the organization (namespace).
  # @param [Hash] opts the optional parameters
  # @option opts [V2OrgsOrgNameGroupsPostRequest] :v2_orgs_org_name_groups_post_request 
  # @return [OrgGroup]
  describe 'v2_orgs_org_name_groups_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
