=begin
#Docker HUB API

#Docker Hub is a service provided by Docker for finding and sharing container images with your team.  It is the world's largest library and community for container images.  In addition to the [Docker Hub UI](https://docs.docker.com/docker-hub/) and [Docker Hub CLI tool](https://github.com/docker/hub-tool#readme) (currently experimental), Docker provides an API that allows you to interact with Docker Hub.  Browse through the Docker Hub API documentation to explore the supported endpoints. 

The version of the OpenAPI document: 2-beta

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'spec_helper'
require 'json'

# Unit tests for DockerHub::OrgSettingsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'OrgSettingsApi' do
  before do
    # run before each test
    @api_instance = DockerHub::OrgSettingsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of OrgSettingsApi' do
    it 'should create an instance of OrgSettingsApi' do
      expect(@api_instance).to be_instance_of(DockerHub::OrgSettingsApi)
    end
  end

  # unit tests for v2_orgs_name_settings_get
  # Get organization settings
  # Returns organization settings by name. 
  # @param name Name of the organization.
  # @param [Hash] opts the optional parameters
  # @return [OrgSettings]
  describe 'v2_orgs_name_settings_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v2_orgs_name_settings_put
  # Update organization settings
  # Updates an organization&#39;s settings. Some settings are only used when the organization is on a business subscription.  ***Only users with administrative privileges for the organization (owner role) can modify these settings.***  The following settings are only used on a business subscription: - &#x60;restricted_images&#x60; 
  # @param name Name of the organization.
  # @param v2_orgs_name_settings_put_request 
  # @param [Hash] opts the optional parameters
  # @return [OrgSettings]
  describe 'v2_orgs_name_settings_put test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
