=begin
#Docker HUB API

#Docker Hub is a service provided by Docker for finding and sharing container images with your team.  It is the world's largest library and community for container images.  In addition to the [Docker Hub UI](https://docs.docker.com/docker-hub/) and [Docker Hub CLI tool](https://github.com/docker/hub-tool#readme) (currently experimental), Docker provides an API that allows you to interact with Docker Hub.  Browse through the Docker Hub API documentation to explore the supported endpoints. 

The version of the OpenAPI document: 2-beta

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'spec_helper'
require 'json'

# Unit tests for DockerHub::OrgAccessTokensApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'OrgAccessTokensApi' do
  before do
    # run before each test
    @api_instance = DockerHub::OrgAccessTokensApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of OrgAccessTokensApi' do
    it 'should create an instance of OrgAccessTokensApi' do
      expect(@api_instance).to be_instance_of(DockerHub::OrgAccessTokensApi)
    end
  end

  # unit tests for v2_orgs_name_access_tokens_get
  # List access tokens
  # List access tokens for an organization. 
  # @param [Hash] opts the optional parameters
  # @option opts [Float] :page 
  # @option opts [Float] :page_size 
  # @return [GetOrgAccessTokensResponse]
  describe 'v2_orgs_name_access_tokens_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v2_orgs_name_access_tokens_post
  # Create access token
  # Create an access token for an organization. 
  # @param create_org_access_token_request 
  # @param [Hash] opts the optional parameters
  # @return [CreateOrgAccessTokenResponse]
  describe 'v2_orgs_name_access_tokens_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v2_orgs_org_name_access_tokens_access_token_id_delete
  # Delete access token
  # Delete a specific access token for an organization. This action cannot be undone. 
  # @param org_name Name of the organization (namespace).
  # @param access_token_id The ID of the access token to retrieve
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'v2_orgs_org_name_access_tokens_access_token_id_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v2_orgs_org_name_access_tokens_access_token_id_get
  # Get access token
  # Get details of a specific access token for an organization. 
  # @param org_name Name of the organization (namespace).
  # @param access_token_id The ID of the access token to retrieve
  # @param [Hash] opts the optional parameters
  # @return [GetOrgAccessTokenResponse]
  describe 'v2_orgs_org_name_access_tokens_access_token_id_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v2_orgs_org_name_access_tokens_access_token_id_patch
  # Update access token
  # Update a specific access token for an organization. 
  # @param org_name Name of the organization (namespace).
  # @param access_token_id The ID of the access token to retrieve
  # @param update_org_access_token_request 
  # @param [Hash] opts the optional parameters
  # @return [UpdateOrgAccessTokenResponse]
  describe 'v2_orgs_org_name_access_tokens_access_token_id_patch test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
