=begin
#Docker HUB API

#Docker Hub is a service provided by Docker for finding and sharing container images with your team.  It is the world's largest library and community for container images.  In addition to the [Docker Hub UI](https://docs.docker.com/docker-hub/) and [Docker Hub CLI tool](https://github.com/docker/hub-tool#readme) (currently experimental), Docker provides an API that allows you to interact with Docker Hub.  Browse through the Docker Hub API documentation to explore the supported endpoints. 

The version of the OpenAPI document: 2-beta

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'spec_helper'
require 'json'

# Unit tests for DockerHub::OrgsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'OrgsApi' do
  before do
    # run before each test
    @api_instance = DockerHub::OrgsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of OrgsApi' do
    it 'should create an instance of OrgsApi' do
      expect(@api_instance).to be_instance_of(DockerHub::OrgsApi)
    end
  end

  # unit tests for v2_orgs_org_name_members_export_get
  # Export org members CSV
  # Export members of an organization as a CSV  &lt;span class&#x3D;\&quot;oat\&quot;&gt;&lt;/span&gt; 
  # @param org_name Name of the organization (namespace).
  # @param [Hash] opts the optional parameters
  # @return [Array<V2OrgsOrgNameMembersExportGet200ResponseInner>]
  describe 'v2_orgs_org_name_members_export_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v2_orgs_org_name_members_get
  # List org members
  # Returns a list of members for an organization.  _The following fields are only visible to orgs with insights enabled._  - &#x60;last_logged_in_at&#x60; - &#x60;last_seen_at&#x60; - &#x60;last_desktop_version&#x60;  To make visible, please see [View Insights for organization users](https://docs.docker.com/admin/organization/insights/#view-insights-for-organization-users).  &lt;span class&#x3D;\&quot;oat\&quot;&gt;&lt;/span&gt; 
  # @param org_name Name of the organization (namespace).
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :search Search term.
  # @option opts [Integer] :page Page number (starts on 1).
  # @option opts [Integer] :page_size Number of items (rows) per page.
  # @option opts [Boolean] :invites Include invites in the response.
  # @option opts [String] :type 
  # @option opts [String] :role 
  # @return [Array<OrgMemberPaginated>]
  describe 'v2_orgs_org_name_members_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v2_orgs_org_name_members_username_delete
  # Remove member from org
  # Removes the member from the org, ie. all groups in the org, unless they&#39;re the last owner  &lt;span class&#x3D;\&quot;oat\&quot;&gt;&lt;/span&gt; 
  # @param org_name Name of the organization (namespace).
  # @param username Username, identifier for the user (namespace, DockerID).
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'v2_orgs_org_name_members_username_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v2_orgs_org_name_members_username_put
  # Update org member (role)
  # Updates the role of a member in the organization. ***Only users in the \&quot;owners\&quot; group of the organization can use this endpoint.***  &lt;span class&#x3D;\&quot;oat\&quot;&gt;&lt;/span&gt; 
  # @param org_name Name of the organization (namespace).
  # @param username Username, identifier for the user (namespace, DockerID).
  # @param v2_orgs_org_name_members_username_put_request 
  # @param [Hash] opts the optional parameters
  # @return [OrgMember]
  describe 'v2_orgs_org_name_members_username_put test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
