=begin
#Docker HUB API

#Docker Hub is a service provided by Docker for finding and sharing container images with your team.  It is the world's largest library and community for container images.  In addition to the [Docker Hub UI](https://docs.docker.com/docker-hub/) and [Docker Hub CLI tool](https://github.com/docker/hub-tool#readme) (currently experimental), Docker provides an API that allows you to interact with Docker Hub.  Browse through the Docker Hub API documentation to explore the supported endpoints. 

The version of the OpenAPI document: 2-beta

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.2.0

=end

require 'spec_helper'
require 'json'

# Unit tests for DockerHub::RepositoriesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'RepositoriesApi' do
  before do
    # run before each test
    @api_instance = DockerHub::RepositoriesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of RepositoriesApi' do
    it 'should create an instance of RepositoriesApi' do
      expect(@api_instance).to be_instance_of(DockerHub::RepositoriesApi)
    end
  end

  # unit tests for check_repository
  # Check repository in a namespace
  # Check a repository within the specified namespace (organization or user).  Public repositories are accessible to everyone, while private repositories require appropriate authentication and permissions. 
  # @param namespace 
  # @param repository 
  # @param [Hash] opts the optional parameters
  # @return [RepositoryInfo]
  describe 'check_repository test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_repository
  # Create a new repository
  # Creates a new repository within the specified namespace. The repository will be created with the provided metadata including name, description, and privacy settings. 
  # @param namespace 
  # @param repo_creation_request 
  # @param [Hash] opts the optional parameters
  # @return [RepositoryInfo]
  describe 'create_repository test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_repository_group
  # Assign a group (Team) to a repository for access
  # @param namespace 
  # @param repository 
  # @param repository_group_creation_request 
  # @param [Hash] opts the optional parameters
  # @return [RepositoryGroup]
  describe 'create_repository_group test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_repository
  # Get repository in a namespace
  # Returns a repository within the specified namespace (organization or user).  Public repositories are accessible to everyone, while private repositories require appropriate authentication and permissions. 
  # @param namespace 
  # @param repository 
  # @param [Hash] opts the optional parameters
  # @return [RepositoryInfo]
  describe 'get_repository test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_repository_tag
  # Read repository tag
  # @param namespace 
  # @param repository 
  # @param tag 
  # @param [Hash] opts the optional parameters
  # @return [Tag]
  describe 'get_repository_tag test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_namespace_repositories
  # List repositories in a namespace
  # Returns a list of repositories within the specified namespace (organization or user).  Public repositories are accessible to everyone, while private repositories require appropriate authentication and permissions. 
  # @param namespace 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page Page number to get. Defaults to 1.
  # @option opts [Integer] :page_size Number of repositories to get per page. Defaults to 10. Max of 100.
  # @option opts [String] :name Filter repositories by name (partial match).
  # @option opts [String] :ordering Order repositories by the specified field. Prefix with &#39;-&#39; for descending order. Available options: - &#x60;name&#x60; / &#x60;-name&#x60;: Repository name (ascending/descending) - &#x60;last_updated&#x60; / &#x60;-last_updated&#x60;: Last update time (ascending/descending) - &#x60;pull_count&#x60; / &#x60;-pull_count&#x60;: Number of pulls (ascending/descending) 
  # @return [ListRepositoriesResponse]
  describe 'list_namespace_repositories test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_repository_tags
  # List repository tags
  # @param namespace 
  # @param repository 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page Page number to get. Defaults to 1.
  # @option opts [Integer] :page_size Number of items to get per page. Defaults to 10. Max of 100.
  # @return [PaginatedTags]
  describe 'list_repository_tags test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_repository_immutable_tags
  # Update repository immutable tags
  # Updates the immutable tags configuration for this repository.  **Only users with administrative privileges for the repository can modify these settings.** 
  # @param namespace 
  # @param repository 
  # @param update_repository_immutable_tags_request 
  # @param [Hash] opts the optional parameters
  # @return [RepositoryInfo]
  describe 'update_repository_immutable_tags test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v2_namespaces_namespace_repositories_repository_tags_head
  # Check repository tags
  # @param namespace 
  # @param repository 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'v2_namespaces_namespace_repositories_repository_tags_head test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v2_namespaces_namespace_repositories_repository_tags_tag_head
  # Check repository tag
  # @param namespace 
  # @param repository 
  # @param tag 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'v2_namespaces_namespace_repositories_repository_tags_tag_head test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for verify_repository_immutable_tags
  # Verify repository immutable tags
  # Validates  the immutable tags regex pass in parameter and returns a list of tags matching it in this repository.  **Only users with administrative privileges for the repository call this endpoint.** 
  # @param namespace 
  # @param repository 
  # @param immutable_tags_verify_request 
  # @param [Hash] opts the optional parameters
  # @return [ImmutableTagsVerifyResponse]
  describe 'verify_repository_immutable_tags test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
