=begin
#Docker HUB API

#Docker Hub is a service provided by Docker for finding and sharing container images with your team.  It is the world's largest library and community for container images.  In addition to the [Docker Hub UI](https://docs.docker.com/docker-hub/) and [Docker Hub CLI tool](https://github.com/docker/hub-tool#readme) (currently experimental), Docker provides an API that allows you to interact with Docker Hub.  Browse through the Docker Hub API documentation to explore the supported endpoints. 

The version of the OpenAPI document: 2-beta

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'spec_helper'
require 'json'

# Unit tests for DockerHub::ScimApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ScimApi' do
  before do
    # run before each test
    @api_instance = DockerHub::ScimApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ScimApi' do
    it 'should create an instance of ScimApi' do
      expect(@api_instance).to be_instance_of(DockerHub::ScimApi)
    end
  end

  # unit tests for v2_scim20_resource_types_get
  # List resource types
  # Returns all resource types supported for the SCIM configuration. 
  # @param [Hash] opts the optional parameters
  # @return [V2Scim20ResourceTypesGet200Response]
  describe 'v2_scim20_resource_types_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v2_scim20_resource_types_name_get
  # Get a resource type
  # Returns a resource type by name. 
  # @param name 
  # @param [Hash] opts the optional parameters
  # @return [ScimResourceType]
  describe 'v2_scim20_resource_types_name_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v2_scim20_schemas_get
  # List schemas
  # Returns all schemas supported for the SCIM configuration. 
  # @param [Hash] opts the optional parameters
  # @return [V2Scim20SchemasGet200Response]
  describe 'v2_scim20_schemas_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v2_scim20_schemas_id_get
  # Get a schema
  # Returns a schema by ID. 
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [ScimSchema]
  describe 'v2_scim20_schemas_id_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v2_scim20_service_provider_config_get
  # Get service provider config
  # Returns a service provider config for Docker&#39;s configuration. 
  # @param [Hash] opts the optional parameters
  # @return [ScimServiceProviderConfig]
  describe 'v2_scim20_service_provider_config_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v2_scim20_users_get
  # List users
  # Returns paginated users for an organization. Use &#x60;startIndex&#x60; and &#x60;count&#x60; query parameters to receive paginated results.  **Sorting:**  Sorting allows you to specify the order in which resources are returned by specifying a combination of &#x60;sortBy&#x60; and &#x60;sortOrder&#x60; query parameters.  The &#x60;sortBy&#x60; parameter specifies the attribute whose value will be used to order the returned responses. The &#x60;sortOrder&#x60; parameter defines the order in which the &#x60;sortBy&#x60; parameter is applied. Allowed values are \&quot;ascending\&quot; and \&quot;descending\&quot;.  **Filtering:**  You can request a subset of resources by specifying the &#x60;filter&#x60; query parameter containing a filter expression. Attribute names and attribute operators used in filters are case insensitive. The filter parameter must contain at least one valid expression. Each expression must contain an attribute name followed by an attribute operator and an optional value.  Supported operators are listed below.  - &#x60;eq&#x60; equal - &#x60;ne&#x60; not equal - &#x60;co&#x60; contains - &#x60;sw&#x60; starts with - &#x60;and&#x60; Logical \&quot;and\&quot; - &#x60;or&#x60; Logical \&quot;or\&quot; - &#x60;not&#x60; \&quot;Not\&quot; function - &#x60;()&#x60; Precedence grouping 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :start_index 
  # @option opts [Integer] :count 
  # @option opts [String] :filter 
  # @option opts [String] :attributes Comma delimited list of attributes to limit to in the response.
  # @option opts [String] :sort_order 
  # @option opts [String] :sort_by User attribute to sort by.
  # @return [V2Scim20UsersGet200Response]
  describe 'v2_scim20_users_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v2_scim20_users_id_get
  # Get a user
  # Returns a user by ID. 
  # @param id The user ID.
  # @param [Hash] opts the optional parameters
  # @return [ScimUser]
  describe 'v2_scim20_users_id_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v2_scim20_users_id_put
  # Update a user
  # Updates a user. This route is used to change the user&#39;s name, activate, and deactivate the user. 
  # @param id The user ID.
  # @param v2_scim20_users_id_put_request 
  # @param [Hash] opts the optional parameters
  # @return [ScimUser]
  describe 'v2_scim20_users_id_put test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for v2_scim20_users_post
  # Create user
  # Creates a user. If the user already exists by email, they are assigned to the organization on the \&quot;company\&quot; team. 
  # @param v2_scim20_users_post_request 
  # @param [Hash] opts the optional parameters
  # @return [ScimUser]
  describe 'v2_scim20_users_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
