=begin
#Docker HUB API

#Docker Hub is a service provided by Docker for finding and sharing container images with your team.  It is the world's largest library and community for container images.  In addition to the [Docker Hub UI](https://docs.docker.com/docker-hub/) and [Docker Hub CLI tool](https://github.com/docker/hub-tool#readme) (currently experimental), Docker provides an API that allows you to interact with Docker Hub.  Browse through the Docker Hub API documentation to explore the supported endpoints. 

The version of the OpenAPI document: 2-beta

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'date'
require 'time'

module DockerHub
  class OrgMember < ApiModelBase
    # The UUID trimmed
    attr_accessor :id

    attr_accessor :company

    attr_accessor :date_joined

    attr_accessor :full_name

    attr_accessor :gravatar_email

    attr_accessor :gravatar_url

    attr_accessor :location

    attr_accessor :profile_url

    attr_accessor :type

    attr_accessor :username

    # User's email address
    attr_accessor :email

    # User's role in the Organization
    attr_accessor :role

    # Groups (Teams) that the user is member of
    attr_accessor :groups

    # If the organization has verified domains, members that have email addresses outside of those domains will be flagged as guests.
    attr_accessor :is_guest

    # The user's email primary address.
    attr_accessor :primary_email

    # Last time the user logged in. To access this field, you must have insights visible for your organization. See  [Insights](https://docs.docker.com/admin/organization/insights/#view-insights-for-organization-users). 
    attr_accessor :last_logged_in_at

    # Last time the user was seen. To access this field, you must have insights visible for your organization. See  [Insights](https://docs.docker.com/admin/organization/insights/#view-insights-for-organization-users). 
    attr_accessor :last_seen_at

    # Last desktop version the user used. To access this field, you must have insights visible for your organization. See  [Insights](https://docs.docker.com/admin/organization/insights/#view-insights-for-organization-users). 
    attr_accessor :last_desktop_version

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'company' => :'company',
        :'date_joined' => :'date_joined',
        :'full_name' => :'full_name',
        :'gravatar_email' => :'gravatar_email',
        :'gravatar_url' => :'gravatar_url',
        :'location' => :'location',
        :'profile_url' => :'profile_url',
        :'type' => :'type',
        :'username' => :'username',
        :'email' => :'email',
        :'role' => :'role',
        :'groups' => :'groups',
        :'is_guest' => :'is_guest',
        :'primary_email' => :'primary_email',
        :'last_logged_in_at' => :'last_logged_in_at',
        :'last_seen_at' => :'last_seen_at',
        :'last_desktop_version' => :'last_desktop_version'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'company' => :'String',
        :'date_joined' => :'String',
        :'full_name' => :'String',
        :'gravatar_email' => :'String',
        :'gravatar_url' => :'String',
        :'location' => :'String',
        :'profile_url' => :'String',
        :'type' => :'String',
        :'username' => :'String',
        :'email' => :'String',
        :'role' => :'String',
        :'groups' => :'Array<String>',
        :'is_guest' => :'Boolean',
        :'primary_email' => :'String',
        :'last_logged_in_at' => :'Time',
        :'last_seen_at' => :'Time',
        :'last_desktop_version' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # List of class defined in allOf (OpenAPI v3)
    def self.openapi_all_of
      [
      :'User'
      ]
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `DockerHub::OrgMember` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `DockerHub::OrgMember`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.key?(:'company')
        self.company = attributes[:'company']
      end

      if attributes.key?(:'date_joined')
        self.date_joined = attributes[:'date_joined']
      end

      if attributes.key?(:'full_name')
        self.full_name = attributes[:'full_name']
      end

      if attributes.key?(:'gravatar_email')
        self.gravatar_email = attributes[:'gravatar_email']
      end

      if attributes.key?(:'gravatar_url')
        self.gravatar_url = attributes[:'gravatar_url']
      end

      if attributes.key?(:'location')
        self.location = attributes[:'location']
      end

      if attributes.key?(:'profile_url')
        self.profile_url = attributes[:'profile_url']
      end

      if attributes.key?(:'type')
        self.type = attributes[:'type']
      end

      if attributes.key?(:'username')
        self.username = attributes[:'username']
      end

      if attributes.key?(:'email')
        self.email = attributes[:'email']
      end

      if attributes.key?(:'role')
        self.role = attributes[:'role']
      end

      if attributes.key?(:'groups')
        if (value = attributes[:'groups']).is_a?(Array)
          self.groups = value
        end
      end

      if attributes.key?(:'is_guest')
        self.is_guest = attributes[:'is_guest']
      end

      if attributes.key?(:'primary_email')
        self.primary_email = attributes[:'primary_email']
      end

      if attributes.key?(:'last_logged_in_at')
        self.last_logged_in_at = attributes[:'last_logged_in_at']
      end

      if attributes.key?(:'last_seen_at')
        self.last_seen_at = attributes[:'last_seen_at']
      end

      if attributes.key?(:'last_desktop_version')
        self.last_desktop_version = attributes[:'last_desktop_version']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      type_validator = EnumAttributeValidator.new('String', ["User", "Org"])
      return false unless type_validator.valid?(@type)
      role_validator = EnumAttributeValidator.new('String', ["Owner", "Member", "Invitee"])
      return false unless role_validator.valid?(@role)
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] type Object to be assigned
    def type=(type)
      @type = type
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] role Object to be assigned
    def role=(role)
      @role = role
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          company == o.company &&
          date_joined == o.date_joined &&
          full_name == o.full_name &&
          gravatar_email == o.gravatar_email &&
          gravatar_url == o.gravatar_url &&
          location == o.location &&
          profile_url == o.profile_url &&
          type == o.type &&
          username == o.username &&
          email == o.email &&
          role == o.role &&
          groups == o.groups &&
          is_guest == o.is_guest &&
          primary_email == o.primary_email &&
          last_logged_in_at == o.last_logged_in_at &&
          last_seen_at == o.last_seen_at &&
          last_desktop_version == o.last_desktop_version
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, company, date_joined, full_name, gravatar_email, gravatar_url, location, profile_url, type, username, email, role, groups, is_guest, primary_email, last_logged_in_at, last_seen_at, last_desktop_version].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
