=begin
#Docker HUB API

#Docker Hub is a service provided by Docker for finding and sharing container images with your team.  It is the world's largest library and community for container images.  In addition to the [Docker Hub UI](https://docs.docker.com/docker-hub/) and [Docker Hub CLI tool](https://github.com/docker/hub-tool#readme) (currently experimental), Docker provides an API that allows you to interact with Docker Hub.  Browse through the Docker Hub API documentation to explore the supported endpoints. 

The version of the OpenAPI document: 2-beta

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.2.0

=end

require 'date'
require 'time'

module DockerHub
  class RepositoryListEntry
    # Name of the repository
    attr_accessor :name

    # Namespace (organization or username) that owns the repository
    attr_accessor :namespace

    # Type of repository
    attr_accessor :repository_type

    # Repository status code
    attr_accessor :status

    # Human-readable repository status
    attr_accessor :status_description

    # Repository description
    attr_accessor :description

    # Whether the repository is private
    attr_accessor :is_private

    # Number of users who starred this repository
    attr_accessor :star_count

    # Total number of pulls for this repository
    attr_accessor :pull_count

    # ISO 8601 timestamp of when the repository was last updated
    attr_accessor :last_updated

    # ISO 8601 timestamp of when the repository was last modified
    attr_accessor :last_modified

    # ISO 8601 timestamp of when the repository was created
    attr_accessor :date_registered

    # User's affiliation with the repository (empty string if no affiliation)
    attr_accessor :affiliation

    # Media types supported by this repository
    attr_accessor :media_types

    # Content types supported by this repository
    attr_accessor :content_types

    # Categories associated with this repository
    attr_accessor :categories

    # Storage size in bytes used by this repository
    attr_accessor :storage_size

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'name' => :'name',
        :'namespace' => :'namespace',
        :'repository_type' => :'repository_type',
        :'status' => :'status',
        :'status_description' => :'status_description',
        :'description' => :'description',
        :'is_private' => :'is_private',
        :'star_count' => :'star_count',
        :'pull_count' => :'pull_count',
        :'last_updated' => :'last_updated',
        :'last_modified' => :'last_modified',
        :'date_registered' => :'date_registered',
        :'affiliation' => :'affiliation',
        :'media_types' => :'media_types',
        :'content_types' => :'content_types',
        :'categories' => :'categories',
        :'storage_size' => :'storage_size'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'name' => :'String',
        :'namespace' => :'String',
        :'repository_type' => :'String',
        :'status' => :'Integer',
        :'status_description' => :'String',
        :'description' => :'String',
        :'is_private' => :'Boolean',
        :'star_count' => :'Integer',
        :'pull_count' => :'Integer',
        :'last_updated' => :'Time',
        :'last_modified' => :'Time',
        :'date_registered' => :'Time',
        :'affiliation' => :'String',
        :'media_types' => :'Array<String>',
        :'content_types' => :'Array<String>',
        :'categories' => :'Array<Category>',
        :'storage_size' => :'Integer'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'repository_type',
        :'description',
        :'last_updated',
        :'last_modified',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `DockerHub::RepositoryListEntry` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `DockerHub::RepositoryListEntry`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.key?(:'namespace')
        self.namespace = attributes[:'namespace']
      end

      if attributes.key?(:'repository_type')
        self.repository_type = attributes[:'repository_type']
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      end

      if attributes.key?(:'status_description')
        self.status_description = attributes[:'status_description']
      end

      if attributes.key?(:'description')
        self.description = attributes[:'description']
      end

      if attributes.key?(:'is_private')
        self.is_private = attributes[:'is_private']
      end

      if attributes.key?(:'star_count')
        self.star_count = attributes[:'star_count']
      end

      if attributes.key?(:'pull_count')
        self.pull_count = attributes[:'pull_count']
      end

      if attributes.key?(:'last_updated')
        self.last_updated = attributes[:'last_updated']
      end

      if attributes.key?(:'last_modified')
        self.last_modified = attributes[:'last_modified']
      end

      if attributes.key?(:'date_registered')
        self.date_registered = attributes[:'date_registered']
      end

      if attributes.key?(:'affiliation')
        self.affiliation = attributes[:'affiliation']
      end

      if attributes.key?(:'media_types')
        if (value = attributes[:'media_types']).is_a?(Array)
          self.media_types = value
        end
      end

      if attributes.key?(:'content_types')
        if (value = attributes[:'content_types']).is_a?(Array)
          self.content_types = value
        end
      end

      if attributes.key?(:'categories')
        if (value = attributes[:'categories']).is_a?(Array)
          self.categories = value
        end
      end

      if attributes.key?(:'storage_size')
        self.storage_size = attributes[:'storage_size']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if !@star_count.nil? && @star_count < 0
        invalid_properties.push('invalid value for "star_count", must be greater than or equal to 0.')
      end

      if !@pull_count.nil? && @pull_count < 0
        invalid_properties.push('invalid value for "pull_count", must be greater than or equal to 0.')
      end

      if !@storage_size.nil? && @storage_size < 0
        invalid_properties.push('invalid value for "storage_size", must be greater than or equal to 0.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      repository_type_validator = EnumAttributeValidator.new('String', ["image", "plugin", "null"])
      return false unless repository_type_validator.valid?(@repository_type)
      status_description_validator = EnumAttributeValidator.new('String', ["active", "inactive"])
      return false unless status_description_validator.valid?(@status_description)
      return false if !@star_count.nil? && @star_count < 0
      return false if !@pull_count.nil? && @pull_count < 0
      return false if !@storage_size.nil? && @storage_size < 0
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] repository_type Object to be assigned
    def repository_type=(repository_type)
      validator = EnumAttributeValidator.new('String', ["image", "plugin", "null"])
      unless validator.valid?(repository_type)
        fail ArgumentError, "invalid value for \"repository_type\", must be one of #{validator.allowable_values}."
      end
      @repository_type = repository_type
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] status_description Object to be assigned
    def status_description=(status_description)
      validator = EnumAttributeValidator.new('String', ["active", "inactive"])
      unless validator.valid?(status_description)
        fail ArgumentError, "invalid value for \"status_description\", must be one of #{validator.allowable_values}."
      end
      @status_description = status_description
    end

    # Custom attribute writer method with validation
    # @param [Object] star_count Value to be assigned
    def star_count=(star_count)
      if star_count.nil?
        fail ArgumentError, 'star_count cannot be nil'
      end

      if star_count < 0
        fail ArgumentError, 'invalid value for "star_count", must be greater than or equal to 0.'
      end

      @star_count = star_count
    end

    # Custom attribute writer method with validation
    # @param [Object] pull_count Value to be assigned
    def pull_count=(pull_count)
      if pull_count.nil?
        fail ArgumentError, 'pull_count cannot be nil'
      end

      if pull_count < 0
        fail ArgumentError, 'invalid value for "pull_count", must be greater than or equal to 0.'
      end

      @pull_count = pull_count
    end

    # Custom attribute writer method with validation
    # @param [Object] storage_size Value to be assigned
    def storage_size=(storage_size)
      if storage_size.nil?
        fail ArgumentError, 'storage_size cannot be nil'
      end

      if storage_size < 0
        fail ArgumentError, 'invalid value for "storage_size", must be greater than or equal to 0.'
      end

      @storage_size = storage_size
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          name == o.name &&
          namespace == o.namespace &&
          repository_type == o.repository_type &&
          status == o.status &&
          status_description == o.status_description &&
          description == o.description &&
          is_private == o.is_private &&
          star_count == o.star_count &&
          pull_count == o.pull_count &&
          last_updated == o.last_updated &&
          last_modified == o.last_modified &&
          date_registered == o.date_registered &&
          affiliation == o.affiliation &&
          media_types == o.media_types &&
          content_types == o.content_types &&
          categories == o.categories &&
          storage_size == o.storage_size
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [name, namespace, repository_type, status, status_description, description, is_private, star_count, pull_count, last_updated, last_modified, date_registered, affiliation, media_types, content_types, categories, storage_size].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = DockerHub.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
