=begin
#Docker HUB API

#Docker Hub is a service provided by Docker for finding and sharing container images with your team.  It is the world's largest library and community for container images.  In addition to the [Docker Hub UI](https://docs.docker.com/docker-hub/) and [Docker Hub CLI tool](https://github.com/docker/hub-tool#readme) (currently experimental), Docker provides an API that allows you to interact with Docker Hub.  Browse through the Docker Hub API documentation to explore the supported endpoints. 

The version of the OpenAPI document: 2-beta

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.2.0

=end

require 'date'
require 'time'

module DockerHub
  class RepositoryInfo
    # Username of the repository owner
    attr_accessor :user

    # Repository name
    attr_accessor :name

    # Repository namespace
    attr_accessor :namespace

    # Type of the repository
    attr_accessor :repository_type

    # Repository status code
    attr_accessor :status

    # Description of the repository status
    attr_accessor :status_description

    # Short description of the repository
    attr_accessor :description

    # Whether the repository is private
    attr_accessor :is_private

    # Whether the repository has automated builds
    attr_accessor :is_automated

    # Number of stars
    attr_accessor :star_count

    # Number of pulls
    attr_accessor :pull_count

    # ISO 8601 timestamp of when repository was last updated
    attr_accessor :last_updated

    # ISO 8601 timestamp of when repository was last modified
    attr_accessor :last_modified

    # ISO 8601 timestamp of when repository was created
    attr_accessor :date_registered

    # Number of collaborators
    attr_accessor :collaborator_count

    # Repository affiliation
    attr_accessor :affiliation

    # Hub user information
    attr_accessor :hub_user

    # Whether the current user has starred this repository
    attr_accessor :has_starred

    # Full description of the repository
    attr_accessor :full_description

    attr_accessor :permissions

    # Supported media types
    attr_accessor :media_types

    # Supported content types
    attr_accessor :content_types

    # Repository categories
    attr_accessor :categories

    attr_accessor :immutable_tags_settings

    # Storage size in bytes
    attr_accessor :storage_size

    # Source of the repository, where it was created from
    attr_accessor :source

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'user' => :'user',
        :'name' => :'name',
        :'namespace' => :'namespace',
        :'repository_type' => :'repository_type',
        :'status' => :'status',
        :'status_description' => :'status_description',
        :'description' => :'description',
        :'is_private' => :'is_private',
        :'is_automated' => :'is_automated',
        :'star_count' => :'star_count',
        :'pull_count' => :'pull_count',
        :'last_updated' => :'last_updated',
        :'last_modified' => :'last_modified',
        :'date_registered' => :'date_registered',
        :'collaborator_count' => :'collaborator_count',
        :'affiliation' => :'affiliation',
        :'hub_user' => :'hub_user',
        :'has_starred' => :'has_starred',
        :'full_description' => :'full_description',
        :'permissions' => :'permissions',
        :'media_types' => :'media_types',
        :'content_types' => :'content_types',
        :'categories' => :'categories',
        :'immutable_tags_settings' => :'immutable_tags_settings',
        :'storage_size' => :'storage_size',
        :'source' => :'source'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'user' => :'String',
        :'name' => :'String',
        :'namespace' => :'String',
        :'repository_type' => :'String',
        :'status' => :'Integer',
        :'status_description' => :'String',
        :'description' => :'String',
        :'is_private' => :'Boolean',
        :'is_automated' => :'Boolean',
        :'star_count' => :'Integer',
        :'pull_count' => :'Integer',
        :'last_updated' => :'Time',
        :'last_modified' => :'Time',
        :'date_registered' => :'Time',
        :'collaborator_count' => :'Integer',
        :'affiliation' => :'String',
        :'hub_user' => :'String',
        :'has_starred' => :'Boolean',
        :'full_description' => :'String',
        :'permissions' => :'RepoPermissions',
        :'media_types' => :'Array<String>',
        :'content_types' => :'Array<String>',
        :'categories' => :'Array<Category>',
        :'immutable_tags_settings' => :'ImmutableTagsSettings',
        :'storage_size' => :'Integer',
        :'source' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'repository_type',
        :'last_modified',
        :'affiliation',
        :'hub_user',
        :'full_description',
        :'storage_size',
        :'source'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `DockerHub::RepositoryInfo` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `DockerHub::RepositoryInfo`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'user')
        self.user = attributes[:'user']
      else
        self.user = nil
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      else
        self.name = nil
      end

      if attributes.key?(:'namespace')
        self.namespace = attributes[:'namespace']
      else
        self.namespace = nil
      end

      if attributes.key?(:'repository_type')
        self.repository_type = attributes[:'repository_type']
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      else
        self.status = nil
      end

      if attributes.key?(:'status_description')
        self.status_description = attributes[:'status_description']
      else
        self.status_description = nil
      end

      if attributes.key?(:'description')
        self.description = attributes[:'description']
      else
        self.description = nil
      end

      if attributes.key?(:'is_private')
        self.is_private = attributes[:'is_private']
      else
        self.is_private = nil
      end

      if attributes.key?(:'is_automated')
        self.is_automated = attributes[:'is_automated']
      else
        self.is_automated = nil
      end

      if attributes.key?(:'star_count')
        self.star_count = attributes[:'star_count']
      else
        self.star_count = nil
      end

      if attributes.key?(:'pull_count')
        self.pull_count = attributes[:'pull_count']
      else
        self.pull_count = nil
      end

      if attributes.key?(:'last_updated')
        self.last_updated = attributes[:'last_updated']
      else
        self.last_updated = nil
      end

      if attributes.key?(:'last_modified')
        self.last_modified = attributes[:'last_modified']
      end

      if attributes.key?(:'date_registered')
        self.date_registered = attributes[:'date_registered']
      else
        self.date_registered = nil
      end

      if attributes.key?(:'collaborator_count')
        self.collaborator_count = attributes[:'collaborator_count']
      else
        self.collaborator_count = nil
      end

      if attributes.key?(:'affiliation')
        self.affiliation = attributes[:'affiliation']
      end

      if attributes.key?(:'hub_user')
        self.hub_user = attributes[:'hub_user']
      end

      if attributes.key?(:'has_starred')
        self.has_starred = attributes[:'has_starred']
      else
        self.has_starred = nil
      end

      if attributes.key?(:'full_description')
        self.full_description = attributes[:'full_description']
      end

      if attributes.key?(:'permissions')
        self.permissions = attributes[:'permissions']
      else
        self.permissions = nil
      end

      if attributes.key?(:'media_types')
        if (value = attributes[:'media_types']).is_a?(Array)
          self.media_types = value
        end
      else
        self.media_types = nil
      end

      if attributes.key?(:'content_types')
        if (value = attributes[:'content_types']).is_a?(Array)
          self.content_types = value
        end
      else
        self.content_types = nil
      end

      if attributes.key?(:'categories')
        if (value = attributes[:'categories']).is_a?(Array)
          self.categories = value
        end
      else
        self.categories = nil
      end

      if attributes.key?(:'immutable_tags_settings')
        self.immutable_tags_settings = attributes[:'immutable_tags_settings']
      else
        self.immutable_tags_settings = nil
      end

      if attributes.key?(:'storage_size')
        self.storage_size = attributes[:'storage_size']
      end

      if attributes.key?(:'source')
        self.source = attributes[:'source']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @user.nil?
        invalid_properties.push('invalid value for "user", user cannot be nil.')
      end

      if @name.nil?
        invalid_properties.push('invalid value for "name", name cannot be nil.')
      end

      if @namespace.nil?
        invalid_properties.push('invalid value for "namespace", namespace cannot be nil.')
      end

      if @status.nil?
        invalid_properties.push('invalid value for "status", status cannot be nil.')
      end

      if @status_description.nil?
        invalid_properties.push('invalid value for "status_description", status_description cannot be nil.')
      end

      if @description.nil?
        invalid_properties.push('invalid value for "description", description cannot be nil.')
      end

      if @is_private.nil?
        invalid_properties.push('invalid value for "is_private", is_private cannot be nil.')
      end

      if @is_automated.nil?
        invalid_properties.push('invalid value for "is_automated", is_automated cannot be nil.')
      end

      if @star_count.nil?
        invalid_properties.push('invalid value for "star_count", star_count cannot be nil.')
      end

      if @pull_count.nil?
        invalid_properties.push('invalid value for "pull_count", pull_count cannot be nil.')
      end

      if @last_updated.nil?
        invalid_properties.push('invalid value for "last_updated", last_updated cannot be nil.')
      end

      if @date_registered.nil?
        invalid_properties.push('invalid value for "date_registered", date_registered cannot be nil.')
      end

      if @collaborator_count.nil?
        invalid_properties.push('invalid value for "collaborator_count", collaborator_count cannot be nil.')
      end

      if @has_starred.nil?
        invalid_properties.push('invalid value for "has_starred", has_starred cannot be nil.')
      end

      if @permissions.nil?
        invalid_properties.push('invalid value for "permissions", permissions cannot be nil.')
      end

      if @media_types.nil?
        invalid_properties.push('invalid value for "media_types", media_types cannot be nil.')
      end

      if @content_types.nil?
        invalid_properties.push('invalid value for "content_types", content_types cannot be nil.')
      end

      if @categories.nil?
        invalid_properties.push('invalid value for "categories", categories cannot be nil.')
      end

      if @immutable_tags_settings.nil?
        invalid_properties.push('invalid value for "immutable_tags_settings", immutable_tags_settings cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @user.nil?
      return false if @name.nil?
      return false if @namespace.nil?
      return false if @status.nil?
      return false if @status_description.nil?
      return false if @description.nil?
      return false if @is_private.nil?
      return false if @is_automated.nil?
      return false if @star_count.nil?
      return false if @pull_count.nil?
      return false if @last_updated.nil?
      return false if @date_registered.nil?
      return false if @collaborator_count.nil?
      return false if @has_starred.nil?
      return false if @permissions.nil?
      return false if @media_types.nil?
      return false if @content_types.nil?
      return false if @categories.nil?
      return false if @immutable_tags_settings.nil?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          user == o.user &&
          name == o.name &&
          namespace == o.namespace &&
          repository_type == o.repository_type &&
          status == o.status &&
          status_description == o.status_description &&
          description == o.description &&
          is_private == o.is_private &&
          is_automated == o.is_automated &&
          star_count == o.star_count &&
          pull_count == o.pull_count &&
          last_updated == o.last_updated &&
          last_modified == o.last_modified &&
          date_registered == o.date_registered &&
          collaborator_count == o.collaborator_count &&
          affiliation == o.affiliation &&
          hub_user == o.hub_user &&
          has_starred == o.has_starred &&
          full_description == o.full_description &&
          permissions == o.permissions &&
          media_types == o.media_types &&
          content_types == o.content_types &&
          categories == o.categories &&
          immutable_tags_settings == o.immutable_tags_settings &&
          storage_size == o.storage_size &&
          source == o.source
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [user, name, namespace, repository_type, status, status_description, description, is_private, is_automated, star_count, pull_count, last_updated, last_modified, date_registered, collaborator_count, affiliation, hub_user, has_starred, full_description, permissions, media_types, content_types, categories, immutable_tags_settings, storage_size, source].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def self._deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = DockerHub.const_get(type)
        klass.respond_to?(:openapi_any_of) || klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
