=begin
#Docker HUB API

#Docker Hub is a service provided by Docker for finding and sharing container images with your team.  It is the world's largest library and community for container images.  In addition to the [Docker Hub UI](https://docs.docker.com/docker-hub/) and [Docker Hub CLI tool](https://github.com/docker/hub-tool#readme) (currently experimental), Docker provides an API that allows you to interact with Docker Hub.  Browse through the Docker Hub API documentation to explore the supported endpoints. 

The version of the OpenAPI document: 2-beta

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'date'
require 'time'

module DockerHub
  class ScimServiceProviderConfig < ApiModelBase
    attr_accessor :schemas

    attr_accessor :documentation_uri

    attr_accessor :patch

    attr_accessor :bulk

    attr_accessor :filter

    attr_accessor :change_password

    attr_accessor :sort

    attr_accessor :etag

    attr_accessor :authentication_schemes

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'schemas' => :'schemas',
        :'documentation_uri' => :'documentationUri',
        :'patch' => :'patch',
        :'bulk' => :'bulk',
        :'filter' => :'filter',
        :'change_password' => :'changePassword',
        :'sort' => :'sort',
        :'etag' => :'etag',
        :'authentication_schemes' => :'authenticationSchemes'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'schemas' => :'Array<String>',
        :'documentation_uri' => :'String',
        :'patch' => :'ScimServiceProviderConfigPatch',
        :'bulk' => :'ScimServiceProviderConfigBulk',
        :'filter' => :'ScimServiceProviderConfigFilter',
        :'change_password' => :'ScimServiceProviderConfigChangePassword',
        :'sort' => :'ScimServiceProviderConfigSort',
        :'etag' => :'ScimServiceProviderConfigChangePassword',
        :'authentication_schemes' => :'ScimServiceProviderConfigAuthenticationSchemes'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `DockerHub::ScimServiceProviderConfig` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `DockerHub::ScimServiceProviderConfig`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'schemas')
        if (value = attributes[:'schemas']).is_a?(Array)
          self.schemas = value
        end
      end

      if attributes.key?(:'documentation_uri')
        self.documentation_uri = attributes[:'documentation_uri']
      end

      if attributes.key?(:'patch')
        self.patch = attributes[:'patch']
      end

      if attributes.key?(:'bulk')
        self.bulk = attributes[:'bulk']
      end

      if attributes.key?(:'filter')
        self.filter = attributes[:'filter']
      end

      if attributes.key?(:'change_password')
        self.change_password = attributes[:'change_password']
      end

      if attributes.key?(:'sort')
        self.sort = attributes[:'sort']
      end

      if attributes.key?(:'etag')
        self.etag = attributes[:'etag']
      end

      if attributes.key?(:'authentication_schemes')
        self.authentication_schemes = attributes[:'authentication_schemes']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          schemas == o.schemas &&
          documentation_uri == o.documentation_uri &&
          patch == o.patch &&
          bulk == o.bulk &&
          filter == o.filter &&
          change_password == o.change_password &&
          sort == o.sort &&
          etag == o.etag &&
          authentication_schemes == o.authentication_schemes
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [schemas, documentation_uri, patch, bulk, filter, change_password, sort, etag, authentication_schemes].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
